enabled: true
currency: SHARDS

messages:
  chat: true
  action-bar: true

currencies:
  shards:
    balance-placeholder: "%arisshards_balance%"
    take-command: "shards take %player% %price%"

main-menu:
  title: "&8ѕʜᴏᴘ"
  rows: 3
  categories:
    end:
      displayname: "&#0bf592ᴇɴᴅ"
      material: END_STONE
      slot: 11
      lore:
        - "&fClick to view"
    nether:
      displayname: "&#0bf592ɴᴇᴛʜᴇʀ"
      material: MAGMA_BLOCK
      slot: 12
      lore:
        - "&fClick to view"
    gear:
      displayname: "&#0bf592ɢᴇᴀʀ"
      material: TOTEM_OF_UNDYING
      slot: 13
      lore:
        - "&fClick to view"
    food:
      displayname: "&#0bf592ꜰᴏᴏᴅ"
      material: COOKED_BEEF
      slot: 14
      lore:
        - "&fClick to view"
    shards:
      displayname: "&#0bf592sʜᴀʀᴅs"
      material: AMETHYST_SHARD
      slot: 15
      lore:
        - "&fClick to view"

gui:
  quantity-selector:
    title: "&8ᴄᴏɴғɪʀᴍ ᴘᴜʀᴄʜᴀsᴇ"
    rows: 3
    cancel:
      name: "&#e00202ᴄᴀɴᴄᴇʟ"
      slot: 21
      material: RED_STAINED_GLASS_PANE
    confirm:
      name: "&#02de4fᴄᴏɴғɪʀᴍ"
      slot: 23
      material: LIME_STAINED_GLASS_PANE
    add1:
      name: "&a+1"
      slot: 15
      material: LIME_STAINED_GLASS_PANE
    add10:
      name: "&a+10"
      slot: 16
      material: LIME_STAINED_GLASS_PANE
    set64:
      name: "&aĐặt 64"
      slot: 17
      material: LIME_STAINED_GLASS_PANE
    remove1:
      name: "&c-1"
      slot: 11
      material: RED_STAINED_GLASS_PANE
    remove10:
      name: "&c-10"
      slot: 10
      material: RED_STAINED_GLASS_PANE
    remove64:
      name: "&cĐặt 1"
      slot: 9
      material: RED_STAINED_GLASS_PANE
    item-preview:
      slot: 13
      lore:
        - "&fGiá mỗi món: &#0bf52b%price%"
        - "&fSố lượng: &e%amount%x"
        - ""
        - "&fTổng cộng: &#0bf52b%total_price%"
  back-button:
    material: RED_STAINED_GLASS_PANE
    displayname: "&#e00202ʙᴀᴄᴋ"
    lore:
      - "&fClick to return"
  next-page:
    material: ARROW
    displayname: "&#f00f0cɴᴇxᴛ"
    lore:
      - "&fClick to go to next page"
  last-page:
    material: ARROW
    displayname: "&#f00f0cʙᴀᴄᴋ"
    lore:
      - "&fClick to go to last page"
