enabled: true
start-balance: 0
max-balance: 999999999

currencies:
  shards:
    balance-placeholder: "%arisshards_balance%"
    take-command: "shards take %player% %price%"

messages:
  chat: true
  action-bar: true
