enabled: true
max-homes:
  default: 1
  "ariscore.home.2": 2
  "ariscore.home.3": 3
  "ariscore.home.4": 4
  "ariscore.home.5": 5
  "ariscore.home.unlimited": 999
teleport:
  countdown: 5
  allowed-walk-range: 0.1
  cancel-on-move: true
  cancel-on-damage: true
  cancel-on-fly: true
messages:
  chat: true
  action-bar: true
gui:
  enabled: true
