enabled: true
teleport:
  countdown: 5
  allowed-walk-range: 0.1
  safe-teleport: false
request:
  expiration-time: 120
  cooldown: 30
  daily-limit: -1
blacklisted-worlds:
  enabled: true
  worlds:
    - "world_nether"
    - "world_the_end"
messages:
  chat: true
  action-bar: true
gui:
  enabled: true
